# Generated by Django 5.2.1 on 2025-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="device",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="device",
            name="current_fan_speed",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("auto", "Auto"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="current_mode",
            field=models.CharField(
                choices=[
                    ("heating", "Heating"),
                    ("cooling", "Cooling"),
                    ("auto", "Auto"),
                    ("turbo", "Turbo"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="error",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="power",
            field=models.CharField(
                choices=[("off", "Off"), ("on", "On")], default="on", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="target_fan_speed",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("auto", "Auto"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="target_mode",
            field=models.CharField(
                choices=[
                    ("heating", "Heating"),
                    ("cooling", "Cooling"),
                    ("auto", "Auto"),
                    ("turbo", "Turbo"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="type",
            field=models.CharField(
                choices=[
                    ("conditioner", "Conditioner"),
                    ("camera", "Camera"),
                    ("humidifier", "Humidifier"),
                    ("dehumidifier", "Dehumidifier"),
                    ("temperature_sensor", "Temperature Sensor"),
                    ("humidity_sensor", "Humidity Sensor"),
                    ("fan", "Fan"),
                ],
                max_length=20,
            ),
        ),
    ]
