# Generated by Django 5.2.1 on 2025-06-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0002_alter_device_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "density",
                    models.IntegerField(
                        default=None, null=True
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "fan_speed",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("auto", "Auto"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("heating", "Heating"),
                            ("cooling", "Cooling"),
                            ("auto", "Auto"),
                            ("turbo", "Turbo"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "power",
                    models.CharField(
                        choices=[("off", "Off"), ("on", "On")],
                        default="on",
                        max_length=3,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="climate.device"
                    ),
                ),
            ],
        ),
    ]
